export const IDENTIFIERS = {
	BOT: 'bot-framework:identifier:BOT',
	BOOTSTRAP: 'bot-framework:identifier:BOOTSTRAP',
	DEBUG: 'bot-framework:identifier:DEBUG',
	ENTITY_MANAGER: 'bot-framework:identifier:ENTITY_MANAGER',
	EVENT_MANAGER: 'bot-framework:identifier:EVENT_MANAGER',
	LOGGER: 'bot-framework:identifier:LOGGER',
	LOG_LEVEL: 'bot-framework:identifier:LOG_LEVEL',
	MIGRATION: 'bot-framework:identifier:MIGRATION',
	MIGRATION_MANAGER: 'bot-framework:identifier:MIGRATION_MANAGER',
	METHOD_BINDER: 'bot-framework:identifier:METHOD_BINDER',
	CONTROLLER_METHOD_BINDER: 'bot-framework:identifier:CONTROLLER_METHOD_BINDER',
	REPOSITORY: 'bot-framework:identifier:REPOSITORY',
	RESOURCE_SERVICE: 'bot-framework:identifier:RESOURCE_SERVICE',
	SETTINGS_KEYS: 'bot-framework:identifier:SETTINGS_KEYS',
	SETTINGS_SERVICE: 'bot-framework:identifier:SETTINGS_SERVICE',
	TASK_SERVICE: 'bot-framework:identifier:TASK_SERVICE',
	TASK_PROCESS: 'bot-framework:identifier:TASK_PROCESS',
	TASK_PROCESS_FACTORY: 'bot-framework:identifier:TASK_PROCESS_FACTORY',
	UPDATE_MANAGER: 'bot-framework:identifier:UPDATE_MANAGER',
	WINDOW_SERVICE: 'bot-framework:identifier:WINDOW_SERVICE',
};
